# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml README.md ./
COPY food_tracker.py ./

# Create data directories
RUN mkdir -p data/users data/logs

# Install dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends gcc libssl-dev libffi-dev && \
    pip install --no-cache-dir "httpx>=0.28.1" "mcp[cli]>=1.6.0" "pydantic>=2.11.1" && \
    apt-get remove -y gcc libssl-dev libffi-dev && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/*

# Expose nothing (stdio)

# Default command
CMD ["python", "food_tracker.py"]
